name: macos

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout MCAD
      run: |
        git submodule update --init --recursive
    - name: Setup Homebrew
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        ./scripts/macosx-build-homebrew.sh
    - name: Build OpenSCAD
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON -DCMAKE_OSX_ARCHITECTURES=arm64;x86_64
        make -j2
